repos:
    - repo: https://github.com/dubzn/pre-commit-cairo.git
      rev: v0.1.4
      hooks:
          - id: scarb-fmt
            args: [--check]
          - id: foundry-test
            args: []
